#!/bin/bash

# Basic split pattern:
# +----------------------------------+
# |                |                 |
# |                |                 |
# |                |-----------------|
# |                |                 |
# |                |                 |
# |                |-----------------|
# |                |                 |
# +----------------------------------+
# splits into default split in a detached manner, using $SPLIT local var
# @arg 1: the split arg, optional
function default_split() {
  split=$SPLIT
  [ ! $SPLIT ] && split=$1 && shift
  [ ! $attach ] && ([ ! $TMUX ] && attach="a -t $SESSION" || attach="")
  [ ! $detach ] && ([ ! $TMUX ] && detach="detach" || detach="")
  tmux $attach \; \
    split-window -h \; \
    select-pane -t $split \; \
    split-window \; \
    select-pane -t $split \; \
    split-window \; \
    resize-pane -t $(( $split + 1 )) -D 17 \; \
    resize-pane -t $split -D 8 \; \
    select-pane -t $(( $split + 2 )) \; \
    split-window \; \
    select-pane -t $(( 4 - $split * 4 )) \; \
    split-window \; \
    resize-pane -D 26 \; \
    select-pane -t $(( 4 - $split * 4 )) \; \
    $detach
}

# @arg 1: either the split var or the command to run in the top side pane
# @arg 2: the command to run in the middle side pane
send_keys() {
  tmux $attach \; \
    select-pane -t $split \; \
    send-keys -t $split "$1" C-m \; \
    select-pane -t $(( $split + 1 )) \; \
    send-keys -t $(( $split + 1 )) "$2" C-m \; \
    select-pane -t $(( 2 - $split * 2 )) \; \
    $detach
}

# Creates a configured tmux session
function create_session() {

  tmux new -s $SESSION -d \; \
    rename-window "main"

  default_split

  configure || tmux a -dt $SESSION \; select-pane -t $(( 2 - $SPLIT * 2 ))
}
