#!/bin/bash

# Basic split pattern:
# +----------------------------------+
# |                |                 |
# |                |                 |
# |                |                 |
# |                |-----------------|
# |                |                 |
# |                |                 |
# |                |                 |
# +----------------------------------+
function default_split() {
  echo $SPLIT
  tmux a -t $SESSION \; \
    split-window -h \; \
    select-pane -t $SPLIT \; \
    split-window \; \
    detach
}

# Creates a configured tmux session
function create_session() {

  tmux new -s $SESSION -d \; \
    rename-window "main" \; \

  default_split

  configure || tmux a -dt $SESSION \; select-pane -t $(( 2 - $SPLIT * 2 ))
}
