#!/bin/bash

SESSION="home"
if [ -r ~/.tmux_google ];
  then SESSION="work";
fi

function create_session() {
  tmux new -s $SESSION -d \; \
    split-window -h \; \
    select-pane -t 1 \; \
    split-window \; \
    send-keys -t 2 "cd ~/dotfiles" C-m \; \
    send-keys -t 2 "vim ." C-m \; \

  # If at work, configure the main and top-right windows.
  if [ -r ~/.tmux_google ];
    then . ~/.tmux_google;
  else
    tmux a -t $SESSION \; \
      send-keys -t 1 "tmux clock-mode" C-m \; \
      select-pane -t 0
  fi
}

# Either attach to an existing session or create a new one that's detached
tmux a -t $SESSION || create_session
