#!/bin/bash

source ~/dotfiles/tmux/tmux/session_fns
if [ -r ~/.tmux.$HOSTNAME ]; then
  source ~/.tmux.$HOSTNAME
fi

set_session || SESSION=""

# Parse input args (supports specifying multi without specifying split as well)
while getopts ":r:m:c:" opt; do
  case $opt in
    m) MULTI="$OPTARG"
      ;;
    c) CLIENT="$OPTARG"
      ;;
    \?) echo "Invalid option -$OPTARG" >&2
  esac
done

# Either attach to an existing session or create a new one
reattach || tmux a -dt $SESSION || create_session
