# ==============================================================================
# Opacity
# ==============================================================================
active-opacity = 1;
inactive-opacity-override = false;

opacity-rule = [
  "99:name *= 'i3lock'",    # Lock screen
  "99:_NET_WM_STATE = '_NET_WM_STATE_FULLSCREEN'",   # Fullscreen
  "80:fullscreen && !focused",
];

inactive-window-opacity = 0.1;  # inactive windows transparent
inactive-opacity = 0.5;  # this is how transparent you want them

# A list of conditions of windows that should always be considered focused
focus-exclude = ["class_g *= 'conky'", "class_g *?= 'polybar'"];

# ==============================================================================
# Blur
# ==============================================================================
backend = "glx"
blur-method = "dual_kawase";
blur-strength = 3;
blur-background-exclude = ["class_g *?= 'conky'"];

# ==============================================================================
# Shadow
# ==============================================================================
shadow = true;
shadow-exclude = ["class_g *?= 'Polybar'", "class_g *?= 'conky'",
                  "_NET_WM_STATE = '_NET_WM_STATE_FULLSCREEN'"];

# ==============================================================================
# Borders
# ==============================================================================
corner-radius = 16;
rounded-corners-exclude = ["class_g = 'polybar'"];

# ==============================================================================
# Fade
# ==============================================================================
fading = true;
