#!/bin/bash

THEME="$1"
shift
IMAGES="$@"
imgv="$#"

# normal font color
normal=$(tput sgr0)

warn() {
  yellow=$(tput setaf 3)
  printf "%s\n" "${yellow}$@${normal}"
}

error() {
  red=$(tput setaf 1)
  printf "%s\n" "${red}$@${normal}"
}

# @arg1 the config without the theme
# @arg2 the available themes for the config
no_theme_error() {
  local available=$(echo "$2" | sed "s/\n/ /g")
  error "" "No $1 configuration for theme $THEME." \
    "  Available themes are [${available}]" \
    "Leaving $1 configuration as-is."
}

refresh_display() {
  if [ "$imgv" -lt 1 ]; then
    warn "No images for theme $THEME. Leaving background as-is."
  else
    local display="feh --bg-scale "
    [ "$THEME" = "borealis" ] && display="feh --bg-fill "
    display="$display $IMAGES"
    eval $display
  fi
}

# @arg1 the delimiter
# @arg2 index to extract
extract() {
  awk -F"$1" "{print \$$2}"
}

line_no() {
  extract ':' '1'
}

theme_polybar() {
  if [ ! -r ~/.config/polybar/colors/$THEME.ini ]; then
    local available=`ls --ignore=colors.ini ~/.config/polybar/colors | sed 's/.ini//g'`
    warn "" "Unknown polybar theme $THEME." \
      "  Available themes are: [${available}]" \
      "Using default polybar colors."
    echo "" > ~/.config/polybar/colors/colors.ini
    return
  fi
  echo "include-file = ~/.config/polybar/colors/$THEME.ini" > ~/.config/polybar/colors/colors.ini

  # restart polybar to pick up focus changes in module files
  polybar-msg cmd restart
}

theme_i3() {
  if [ -z "$(grep "^set \$$THEME" ~/.i3/config)" ]; then
    local available=`awk "/# themed/,/# class/" ~/.i3/config | \
      egrep "set .[a-z]+.*" | extract ' ' '2' | sed 's/\$//'`
    no_theme_error "i3" "$available"
    return
  fi
  local current=`egrep -o "^client\.focused .*\$" ~/.i3/config \
    | extract ' ' '2' | sed 's/\$//'`
  sed -i "/^client/s/${current}/\$${THEME}/g" ~/.i3/config
  i3-msg reload
}

theme_tmux() {
  if [ ! -r ~/tmux/colors/$THEME.conf ]; then
    local available=`ls --ignore=colors.conf --ignore=shared.conf ~/tmux/colors | sed 's/.conf//g'`
    no_theme_error "tmux" "$available"
    return
  fi
  echo "source-file ~/tmux/colors/$THEME.conf" > ~/tmux/colors/colors.conf
}

theme_rofi() {
  if [ ! -r "$HOME/.config/rofi/colorschemes/$THEME.rasi" ]; then
    local available=`ls --ignore=general.rasi --ignore=colors.rasi ~/.config/rofi/colorschemes | sed 's/.rasi//g'`
    no_theme_error "rofi" "$available"
    return
  fi
  echo "@import \"$THEME.rasi\"" > ~/.config/rofi/colorschemes/colors.rasi
}

theme_dunst() {
  if [ -r ~/.config/dunst/colors/$THEME.conf ]; then
    cat ~/.config/dunst/colors/$THEME.conf > ~/.config/dunst/dunstrc.d/999-colors.conf
  else
    echo "" > ~/.config/dunst/dunstrc.d/999-colors.conf
    warn "Reset dunst theme to default"
  fi

  # attempt to kill dunst to reload the config (shouldn't be allowed, since
  # daemon started from DBUS)
  pkill dunst
}

theme_ncmpcpp() {
  if [ ! -r "$HOME/.ncmpcpp/$THEME.ini" ]; then
    local available=`ls ~/.ncmpcpp/*.ini | extract '/' '5' | extract '.' '1'`
    no_theme_error "ncmpcpp" "$available"
    return
  fi
  local music_dir=`grep music_directory ~/.config/mpd/mpd.conf | extract '  ' '2'`
  sed "s~%music_dir%~$music_dir~" ~/.ncmpcpp/template > ~/.ncmpcpp/config
  IFS=$'\n'
  for line in $(cat ~/.ncmpcpp/$THEME.ini); do
    local param=`echo $line | extract '=' '1' | sed "s/ *$//g"`
    local value=`echo $line | extract '=' '2' | sed "s/^ *//g"`
    sed -i "s/%$param%/$value/g" ~/.ncmpcpp/config
  done
}

theme_vim() {
  if [ ! -r ~/.vim/colors/$THEME.vim ]; then
    local available=`ls --ignore=colors.vim ~/.vim/colors | sed 's/.vim//g'`
    no_theme_error "vim" "$available"
    return
  fi
  echo "source ~/.vim/colors/$THEME.vim" > ~/.vim/colors/colors.vim
}

theme_others() {
  if [ -z $THEME ]; then
    bold=$(tput bold)
    error "" "${bold}No theme provided; exiting.${normal}"
    exit 1
  fi
  theme_i3
  theme_tmux
  theme_rofi
  theme_ncmpcpp
  theme_vim
  # TODO(zskendall): theme xfce4-terminal for light bg (paracosm)
}

if [ `ps -aux | grep polybar | wc -l` -gt 1 ] ; then
  notify-send -a recolor "changing theme to $THEME"
fi

if [ "$imgv" -ne `xrandr | egrep "[^dis]connected" | wc -l` ]; then
  case $THEME in
    borealis)
      IMAGES="~/dotfiles/images/background_main.jpg ~/dotfiles/images/aurora_secondary.jpg"
      ;;
    nikhita)
      IMAGES="~/dotfiles/images/background_secondary.jpg ~/dotfiles/images/nikhita_secondary.jpg"
      ;;
    astral)
      IMAGES="~/dotfiles/images/astral_main.jpg ~/dotfiles/images/DSC_4419.jpg"
      ;;
    autumnal)
      IMAGES="~/dotfiles/images/autumnal_main.jpg ~/dotfiles/images/autumnal_secondary.jpg"
      ;;
  esac
  imgv=$(echo "$IMAGES" | wc -w) # recount the images
fi
refresh_display

theme_dunst
theme_polybar
theme_others
if [ `ps -aux | grep polybar | wc -l` -gt 1 ] ; then
  notify-send -a recolor "udpated theme to $THEME"
fi
