#!/bin/bash

# Based on rofi setup from ntcarlson:
# https://github.com/ntcarlson/dotfiles/blob/tau/i3/scripts

LOCK=""
LOGOUT=""
RESTART=""
SHUTDOWN=""

rofi_confirm() {
  case "$(echo -e '\n' | rofi -dmenu -theme confirm -mesg "$1")" in
    "") exit 1;;
    "") exit 0;;
  esac
  exit 1
}

list_icons() {
  echo $LOCK
  echo $LOGOUT
  echo $RESTART
  echo $SHUTDOWN
}

handle_option() {
  case "$1" in
    "$LOCK")
        ~/.i3/scripts/locker -i ~/weather.png -l 999999;;
    "$LOGOUT")
        if $(rofi_confirm "$LOGOUT"); then
          i3-msg exit
        fi
        ;;
    "$RESTART")
        if $(rofi_confirm "$RESTART"); then
          reboot
        fi
        ;;
    "$SHUTDOWN")
        if $(rofi_confirm "$SHUTDOWN"); then
          shutdown now
        fi
        ;;
  esac
}

SELECTION="$(list_icons | rofi -dmenu -theme sysmenu -mesg 'System')"
handle_option $SELECTION &
