#!/bin/bash

# Parse the arguments to construct the i3lock command
while getopts ":i:c:w:l:o:" opt; do
  case $opt in
    i) image="$OPTARG"
    ;;
    c) color="$OPTARG"
    ;;
    w) wrong="$OPTARG"
    ;;
    l) idle="$OPTARG"
    ;;
    o) done="$OPTARG"
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    ;;
    :) echo "Option -$OPTARG requires an argument." >&2
    ;;
  esac
done

lock='~/.i3/i3lock.sh -t -e'

# Only set the image if the arg was defined and the file exists. Otherwise,
# check the background color.
if [[ ! -z "$image" ]] && [ -f "$image" ]; then
  lock="$lock -i $image"
elif [[ ! -z "$color" ]]; then
  lock="$lock -c $color"

  # If the background color is black and an idle color wasn't defined, change
  # the idle color to something lighter.
  if [[ "$color" == "000000" ]] && [[ -z "$idle" ]]; then
    lock="$lock -l 595959"
  fi
fi

if [[ ! -z "$wrong" ]]; then
  lock="$lock -w $wrong"
fi

# Set the idle color if an arg was provided and it hasn't already been set.
if [[ ! -z "$idle" ]] && [[ ! "$lock" == *"-l"* ]]; then
  lock="$lock -l $idle"
fi

if [[ ! -z "$done" ]]; then
  lock="$lock -o $done"
fi

eval $lock

# Turn the screen off after a delay.
sleep 25; pgrep i3lock && xset dpms force off
